---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: '{{ molecule_no_log }}'
  tasks:
    - name: Create custom Docker network for AD
      community.docker.docker_network:
        name: molecule-samba-member
        driver: bridge
        ipam_config:
          - subnet: 172.20.0.0/16
            gateway: 172.20.0.1
        state: present

    - name: Log info
      ansible.builtin.debug:
        msg: 'Creating AD-enabled Docker network'
      when: not ansible_check_mode

    - name: Create molecule instance(s)
      community.docker.docker_container:
        name: '{{ item.name }}'
        hostname: '{{ item.hostname | default(item.name) }}'
        image: '{{ item.image }}'
        state: started
        recreate: false
        log_driver: json-file
        command: '{{ item.command | default(''bash -c "while true; do sleep 30; done"'') }}'
        privileged: '{{ item.privileged | default(omit) }}'
        volumes: '{{ item.volumes | default(omit) }}'
        capabilities: '{{ item.capabilities | default(omit) }}'
        exposed_ports: '{{ item.exposed_ports | default(omit) }}'
        published_ports: '{{ item.published_ports | default(omit) }}'
        ulimits: '{{ item.ulimits | default(omit) }}'
        networks:
          - name: '{{ item.networks[0].name }}'
            ipv4_address: '{{ item.networks[0].ipv4_address | default(omit) }}'
        dns_servers: "{{ item.dns_servers | default(['8.8.8.8']) }}"
        etc_hosts: '{{ item.etc_hosts | default(omit) }}'
        env: '{{ item.env | default(omit) }}'
        restart_policy: "{{ item.restart_policy | default('unless-stopped') }}"
        cgroupns_mode: '{{ item.cgroupns_mode | default(omit) }}'
      register: server
      with_items: '{{ molecule_yml.platforms }}'
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      ansible.builtin.async_status:
        jid: '{{ item.ansible_job_id }}'
      register: docker_jobs
      until: docker_jobs.finished
      retries: 300
      delay: 2
      with_items: '{{ server.results }}'
